In [1]:
import pandas as pd
pd.read_excel('vehicles_by_make_fuel_2023_zip.xlsx')

             Make                      Fuel  Vehicles
0       OTHER/UNK                  Gasoline     16917
1           TESLA          Battery Electric      8977
2          TOYOTA                  Gasoline      8471
3             KIA                  Gasoline      7585
4       OTHER/UNK          Battery Electric      3948
5       OTHER/UNK           Hybrid Gasoline      3748
6             BMW                  Gasoline      3478
7         HYUNDAI                  Gasoline      2859
8       CHEVROLET                  Gasoline      2647
9          SUBARU                  Gasoline      2254
10          HONDA                  Gasoline      2114
11      OTHER/UNK            Plug-in Hybrid      2026
12         NISSAN                  Gasoline      1753
13  MERCEDES-BENZ                  Gasoline      1562
14      OTHER/UNK  Diesel and Diesel Hybrid      1435
15            KIA           Hybrid Gasoline      1162
16     LAND ROVER                  Gasoline      1056
17         TOYOTA           Hybrid Gasoline       837
18          MAZDA                  Gasoline       792
19           AUDI                  Gasoline       724
20            GMC                  Gasoline       644
21       CADILLAC                  Gasoline       593
22   FREIGHTLINER  Diesel and Diesel Hybrid       424
23           JEEP                  Gasoline       399
24      CHEVROLET          Battery Electric       310
25        PORSCHE                  Gasoline       262
26           MINI                  Gasoline       249
27  INTERNATIONAL  Diesel and Diesel Hybrid       208
28        GENESIS                  Gasoline       194
29       POLESTAR          Battery Electric       190
30       KENWORTH  Diesel and Diesel Hybrid       185
31           FORD                  Gasoline       174
32          VOLVO  Diesel and Diesel Hybrid       168
33          VOLVO                  Gasoline       160
34            BMW            Plug-in Hybrid       134
35          LEXUS                  Gasoline       125
36          ACURA                  Gasoline       110
37      PETERBILT  Diesel and Diesel Hybrid       102
38      OTHER/UNK               Natural Gas        94
39          LEXUS           Hybrid Gasoline        78
40     VOLKSWAGEN                  Gasoline        69
41      OTHER/UNK                       Unk        63
42           MACK               Natural Gas        35
43            RAM                  Gasoline        32
44         JAGUAR                  Gasoline        24
45            BMW          Battery Electric        23
46      CHEVROLET  Diesel and Diesel Hybrid        23
47            Unk                       Unk        16
48   FREIGHTLINER               Natural Gas        15
49       CADILLAC          Battery Electric        15
50          BUICK                  Gasoline        15
51       KENWORTH               Natural Gas        14
52        HYUNDAI          Battery Electric        13
53       MASERATI                  Gasoline        12
54  MERCEDES-BENZ          Battery Electric        12
55          VOLVO            Plug-in Hybrid        11
56      OTHER/UNK        Hydrogen Fuel Cell         2

In [2]:
df = pd.read_excel('vehicles_by_make_fuel_2023_zip.xlsx')

# Define a dictionary to map old Fuel names to new names
fuel_mapping = {
    'Gasoline': 'Gasoline',
    'Other': 'Other',
    'Diesel and Diesel Hybrid': 'Diesel Fuel',
    'Natural Gas': 'Compressed Natural Gas (CNG)',
    'Hybrid Gasoline': 'Gasoline',
    'Flex-Fuel': 'Ethanol (E-85)',
    'Battery Electric': 'Electricity',
    'Plug-in Hybrid': 'Electricity',
    'Hydrogen Fuel Cell': 'Electricity',
    # Add more mappings if needed
}

# Replace the Fuel names with the assigned names using the replace method
df['Fuel'] = df['Fuel'].replace(fuel_mapping)

# Print the DataFrame to see the updated data
print(df)

             Make                          Fuel  Vehicles
0       OTHER/UNK                      Gasoline     16917
1           TESLA                   Electricity      8977
2          TOYOTA                      Gasoline      8471
3             KIA                      Gasoline      7585
4       OTHER/UNK                   Electricity      3948
5       OTHER/UNK                      Gasoline      3748
6             BMW                      Gasoline      3478
7         HYUNDAI                      Gasoline      2859
8       CHEVROLET                      Gasoline      2647
9          SUBARU                      Gasoline      2254
10          HONDA                      Gasoline      2114
11      OTHER/UNK                   Electricity      2026
12         NISSAN                      Gasoline      1753
13  MERCEDES-BENZ                      Gasoline      1562
14      OTHER/UNK                   Diesel Fuel      1435
15            KIA                      Gasoline      1162
16     LAND ROVER                      Gasoline      1056
17         TOYOTA                      Gasoline       837
18          MAZDA                      Gasoline       792
19           AUDI                      Gasoline       724
20            GMC                      Gasoline       644
21       CADILLAC                      Gasoline       593
22   FREIGHTLINER                   Diesel Fuel       424
23           JEEP                      Gasoline       399
24      CHEVROLET                   Electricity       310
25        PORSCHE                      Gasoline       262
26           MINI                      Gasoline       249
27  INTERNATIONAL                   Diesel Fuel       208
28        GENESIS                      Gasoline       194
29       POLESTAR                   Electricity       190
30       KENWORTH                   Diesel Fuel       185
31           FORD                      Gasoline       174
32          VOLVO                   Diesel Fuel       168
33          VOLVO                      Gasoline       160
34            BMW                   Electricity       134
35          LEXUS                      Gasoline       125
36          ACURA                      Gasoline       110
37      PETERBILT                   Diesel Fuel       102
38      OTHER/UNK  Compressed Natural Gas (CNG)        94
39          LEXUS                      Gasoline        78
40     VOLKSWAGEN                      Gasoline        69
41      OTHER/UNK                           Unk        63
42           MACK  Compressed Natural Gas (CNG)        35
43            RAM                      Gasoline        32
44         JAGUAR                      Gasoline        24
45            BMW                   Electricity        23
46      CHEVROLET                   Diesel Fuel        23
47            Unk                           Unk        16
48   FREIGHTLINER  Compressed Natural Gas (CNG)        15
49       CADILLAC                   Electricity        15
50          BUICK                      Gasoline        15
51       KENWORTH  Compressed Natural Gas (CNG)        14
52        HYUNDAI                   Electricity        13
53       MASERATI                      Gasoline        12
54  MERCEDES-BENZ                   Electricity        12
55          VOLVO                   Electricity        11
56      OTHER/UNK                   Electricity         2

In [3]:
# Define a dictionary to map old Make names to new names
make_mapping = {
    'TOYOTA': 'Toyota',
    'OTHER/UNK': 'Other',
'TOYOTA': 'Passenger Car',
'FORD': 'Passenger Car', 
'CHEVROLET': 'Passenger Car', 
'HONDA': 'Passenger Car', 
'LEXUS': 'Passenger Car', 
'NISSAN': 'Passenger Car', 
'DODGE': 'Passenger Car', 
'MERCEDES-BENZ': 'Passenger Car', 
'BMW': 'Passenger Car', 
'HYUNDAI': 'Passenger Car', 
'VOLKSWAGEN': 'Passenger Car', 
'JEEP': 'Passenger Car', 
'SUBARU': 'Passenger Car', 
'KIA': 'Passenger Car', 
'GMC': 'Passenger Truck',
'MAZDA': 'Passenger Car', 
'ACURA': 'Passenger Car', 
'AUDI': 'Passenger Car', 
'RAM': 'Passenger Truck',
'INFINITI': 'Passenger Car', 
'TESLA': 'Passenger Car', 
'CADILLAC': 'Passenger Car', 
'SCION': 'Passenger Car', 
'PORSCHE': 'Passenger Car', 
'CHRYSLER': 'Passenger Car', 
'VOLVO': 'Passenger Car', 
'MINI': 'Passenger Car', 
'FREIGHTLINER': 'Light Commercial Truck',
'LAND ROVER': 'Passenger Car', 
'BUICK': 'Passenger Car', 
'MITSUBISHI': 'Passenger Car', 
'Unk': 'Other',
'LINCOLN': 'Passenger Car', 
'PONTIAC': 'Passenger Car', 
'PETERBILT': 'Combination Long-haul Truck',
'SATURN': 'Passenger Car', 
'JAGUAR': 'Passenger Car', 
'MERCURY': 'Passenger Car', 
'KENWORTH': 'Combination Long-haul Truck',
'INTERNATIONAL': 'Combination Long-haul Truck',
'ISUZU': 'Single Unit Short-haul Truck',
'HUMMER': 'Passenger Truck',
'FIAT': 'Passenger Car', 
'SUZUKI': 'Passenger Car', 
'OLDSMOBILE': 'Passenger Car', 
'WORKHORSE': 'Light Commercial Truck',
'GENESIS': 'Passenger Car', 
'HINO': 'Single Unit Short-haul Truck',
'SAAB': 'Passenger Car', 
'PLYMOUTH': 'Passenger Car', 
'ALFA ROMEO': 'Passenger Car', 
'AUTOCAR': 'Single Unit Short-haul Truck',
'RIVIAN': 'Passenger Car', 
'GEO': 'Passenger Car', 
'BLUE BIRD': 'School Bus',
'GILLIG': 'Transit Bus',
'THOMAS BUS': 'School Bus',
'NEW FLYER': 'Transit Bus',
'ROADMASTER': 'Single Unit Short-haul Truck',
'MACK': 'Combination Long-haul Truck',
'UNKNOWN': 'Other',
'BENTLEY': 'Passenger Car', 
'FERRARI': 'Passenger Car', 
'MASERATI': 'Passenger Car', 
'IC BUS LLC': 'School Bus',
'SMART': 'Passenger Car', 
'POLESTAR': 'Passenger Car', 
'SPARTAN': 'Combination Long-haul Truck',
'IC BUS': 'School Bus',
'VAN HOOL': 'Transit Bus',
'PIERCE': 'Refuse Truck',
'EL DORADO': 'Transit Bus',
'KALMAR': 'Light Commercial Truck',
'ROLLS-ROYCE': 'Passenger Car', 
'WESTERN STAR': 'Combination Long-haul Truck',
'MOTOR COACH INDUSTRIES': 'Transit Bus',
'BYD COACH AND BUS': 'Transit Bus',
'NORTH AMERICAN BUS INDUSTRIES': 'Transit Bus',
'AMERICAN LAFRANCE': 'Transit Bus',
'KOVATCH MOBLIE EQUIPMENT CORP': 'Other Buses',
'STERLING': 'Combination Long-haul Truck',
'CRANE CARRIER': 'Combination Short-haul Truck',
'LAMBORGHINI': 'Passenger Car', 
'FLXIBLE TRANSIT COACHES': 'Transit Bus',
'ORION': 'Transit Bus',
'ASTON MARTIN': 'Passenger Car', 
'HME': 'Combination Short-haul Truck',
'PREVOST': 'Transit Bus',
'CRUISE': 'Passenger Car',
'AM GENERAL': 'Combination Short-haul Truck',
'LUCID': 'Passenger Car', 
'TMC': 'Single Unit Long-haul Truck',
'GLOBAL ENVIRONMENTAL': 'Transit Bus',
'KOVATCH': 'Other Buses',
'TICO': 'Single Unit Long-haul Truck',
'WHITE/GMC': 'Single Unit Long-haul Truck',
'GREENPOWER MOTOR': 'Transit Bus',
'NORTH AMERICAN': 'Transit Bus',
'NEOPLAN': 'Transit Bus',
'ALLIANZ': 'Combination Short-haul Truck',
'WHITE': 'Light Commercial Truck',
'XOS': 'Transit Bus',
'LODAL': 'Transit Bus',
'PROTERRA': 'Transit Bus',
'ARBOC': 'Transit Bus',
'BLUEBIRD': 'School Bus',
'MOTOR COACH IND': 'Transit Bus',
'MAN TRUCK AND BUS CORPORATION': 'Combination Long-haul Truck',
'CAPACITY': 'Single Unit Short-haul Truck',
'EMERGENCY ONE': 'Refuse Truck',
'BRIGHTDROP': 'Passenger Truck',
'VPG': 'Passenger Car', 
'CATERPILLAR': 'Single Unit Long-haul Truck',
'COUNTRY COACH': 'Motor Home',
'SPECIAL CONSTRUCTION': 'Other',
'FWD': 'Single Unit Short-haul Truck',
'SEAGRAVE': 'Refuse Truck',
'TROLLEY': 'Transit Bus',
'ALEXANDER DENNIS': 'Transit Bus',
'MG': 'Passenger Car', 
'ORANGE EV': 'Transit Bus',
'OSHKOSH': 'Combination Short-haul Truck',
'LOTUS': 'Passenger Car', 

    # Add more mappings if needed
}

# Replace the Make names with the assigned names using the replace method
df['Make'] = df['Make'].replace(make_mapping)

# Print the DataFrame to see the updated data
print(df)

                           Make                          Fuel  Vehicles
0                         Other                      Gasoline     16917
1                 Passenger Car                   Electricity      8977
2                 Passenger Car                      Gasoline      8471
3                 Passenger Car                      Gasoline      7585
4                         Other                   Electricity      3948
5                         Other                      Gasoline      3748
6                 Passenger Car                      Gasoline      3478
7                 Passenger Car                      Gasoline      2859
8                 Passenger Car                      Gasoline      2647
9                 Passenger Car                      Gasoline      2254
10                Passenger Car                      Gasoline      2114
11                        Other                   Electricity      2026
12                Passenger Car                      Gasoline      1753
13                Passenger Car                      Gasoline      1562
14                        Other                   Diesel Fuel      1435
15                Passenger Car                      Gasoline      1162
16                Passenger Car                      Gasoline      1056
17                Passenger Car                      Gasoline       837
18                Passenger Car                      Gasoline       792
19                Passenger Car                      Gasoline       724
20              Passenger Truck                      Gasoline       644
21                Passenger Car                      Gasoline       593
22       Light Commercial Truck                   Diesel Fuel       424
23                Passenger Car                      Gasoline       399
24                Passenger Car                   Electricity       310
25                Passenger Car                      Gasoline       262
26                Passenger Car                      Gasoline       249
27  Combination Long-haul Truck                   Diesel Fuel       208
28                Passenger Car                      Gasoline       194
29                Passenger Car                   Electricity       190
30  Combination Long-haul Truck                   Diesel Fuel       185
31                Passenger Car                      Gasoline       174
32                Passenger Car                   Diesel Fuel       168
33                Passenger Car                      Gasoline       160
34                Passenger Car                   Electricity       134
35                Passenger Car                      Gasoline       125
36                Passenger Car                      Gasoline       110
37  Combination Long-haul Truck                   Diesel Fuel       102
38                        Other  Compressed Natural Gas (CNG)        94
39                Passenger Car                      Gasoline        78
40                Passenger Car                      Gasoline        69
41                        Other                           Unk        63
42  Combination Long-haul Truck  Compressed Natural Gas (CNG)        35
43              Passenger Truck                      Gasoline        32
44                Passenger Car                      Gasoline        24
45                Passenger Car                   Electricity        23
46                Passenger Car                   Diesel Fuel        23
47                        Other                           Unk        16
48       Light Commercial Truck  Compressed Natural Gas (CNG)        15
49                Passenger Car                   Electricity        15
50                Passenger Car                      Gasoline        15
51  Combination Long-haul Truck  Compressed Natural Gas (CNG)        14
52                Passenger Car                   Electricity        13
53                Passenger Car                      Gasoline        12
54                Passenger Car                   Electricity        12
55                Passenger Car                   Electricity        11
56                        Other                   Electricity         2

In [4]:
# Group the DataFrame by 'Make' and 'Fuel' and calculate the sum of 'Vehicles'
grouped_df = df.groupby(['Make', 'Fuel'])['Vehicles'].sum().reset_index()

# Print the DataFrame to see the updated data
print(grouped_df)

                           Make                          Fuel  Vehicles
0   Combination Long-haul Truck  Compressed Natural Gas (CNG)        49
1   Combination Long-haul Truck                   Diesel Fuel       495
2        Light Commercial Truck  Compressed Natural Gas (CNG)        15
3        Light Commercial Truck                   Diesel Fuel       424
4                         Other  Compressed Natural Gas (CNG)        94
5                         Other                   Diesel Fuel      1435
6                         Other                   Electricity      5976
7                         Other                      Gasoline     20665
8                         Other                           Unk        79
9                 Passenger Car                   Diesel Fuel       191
10                Passenger Car                   Electricity      9685
11                Passenger Car                      Gasoline     39758
12              Passenger Truck                      Gasoline       676

In [5]:
# Save the filtered DataFrame as an Excel file (xlsx)
#grouped_df.to_excel('make_Fuel_Vehicles_2018_zip.xlsx', index=False)

In [6]:
# Calculate the total of the 'Vehicles' column in the grouped DataFrame
total_vehicles = grouped_df['Vehicles'].sum()
print("Total number of vehicles:", total_vehicles)

Total number of vehicles: 79542

In [7]:
# Calculate the total of the 'Vehicles' column in the grouped DataFrame
total_vehicles = grouped_df['Vehicles'].sum()
print("Total number of vehicles:", total_vehicles)

Total number of vehicles: 79542

In [8]:
# Filter out rows where 'Make' or 'Fuel' are labeled exactly as 'Other'
grouped_df = grouped_df[~(grouped_df['Make'].str.strip() == 'Other') & ~(grouped_df['Fuel'].str.strip() == 'Other')]


# Print the DataFrame to see the updated data
print(grouped_df)

                           Make                          Fuel  Vehicles
0   Combination Long-haul Truck  Compressed Natural Gas (CNG)        49
1   Combination Long-haul Truck                   Diesel Fuel       495
2        Light Commercial Truck  Compressed Natural Gas (CNG)        15
3        Light Commercial Truck                   Diesel Fuel       424
9                 Passenger Car                   Diesel Fuel       191
10                Passenger Car                   Electricity      9685
11                Passenger Car                      Gasoline     39758
12              Passenger Truck                      Gasoline       676

In [9]:
# Calculate the total of the 'Vehicles' column in the grouped DataFrame
total_vehicles = grouped_df['Vehicles'].sum()
print("Total number of vehicles:", total_vehicles)

Total number of vehicles: 51293

In [10]:
# Filter out rows where 'Make' or 'Fuel' are not labeled exactly as 'Other'
filtered_df = df[(df['Make'] == 'Other') | (df['Fuel'] == 'Other')]

print(filtered_df)

     Make                          Fuel  Vehicles
0   Other                      Gasoline     16917
4   Other                   Electricity      3948
5   Other                      Gasoline      3748
11  Other                   Electricity      2026
14  Other                   Diesel Fuel      1435
38  Other  Compressed Natural Gas (CNG)        94
41  Other                           Unk        63
47  Other                           Unk        16
56  Other                   Electricity         2

In [11]:
# Calculate the total of the 'Vehicles' column in the grouped DataFrame
total_vehicles = filtered_df['Vehicles'].sum()
print("Total number of vehicles:", total_vehicles)

Total number of vehicles: 28249

In [13]:
51293+28249

79542