In [1]:
import pandas as pd
pd.read_excel('vehicles_by_make_fuel_2009_zip.xlsx')

                             Make                      Fuel  Vehicles
0                          TOYOTA                  Gasoline     36974
1                       OTHER/UNK                  Gasoline     27449
2                           HONDA                  Gasoline     25636
3                          NISSAN                  Gasoline     11850
4                           LEXUS                  Gasoline      6270
5                            FORD                  Gasoline      6253
6                   MERCEDES-BENZ                  Gasoline      5931
7                       CHEVROLET                  Gasoline      4924
8                          TOYOTA           Hybrid Gasoline      4587
9                             BMW                  Gasoline      4488
10                      OTHER/UNK                 Flex-Fuel      3780
11                          SCION                  Gasoline      3382
12                      OTHER/UNK  Diesel and Diesel Hybrid      2779
13                        HYUNDAI                  Gasoline      2696
14                     VOLKSWAGEN                  Gasoline      2498
15                      OTHER/UNK           Hybrid Gasoline      2397
16                          ACURA                  Gasoline      1715
17                            KIA                  Gasoline      1637
18                          DODGE                  Gasoline      1635
19                      CHEVROLET                 Flex-Fuel      1476
20                       INFINITI                  Gasoline      1014
21                           FORD                 Flex-Fuel       662
22                           AUDI                  Gasoline       571
23                          MAZDA                  Gasoline       515
24                            GMC                  Gasoline       468
25                      OTHER/UNK               Natural Gas       444
26                   FREIGHTLINER  Diesel and Diesel Hybrid       419
27                           MINI                  Gasoline       340
28                           JEEP                  Gasoline       338
29                         SUBARU                  Gasoline       285
30                  INTERNATIONAL  Diesel and Diesel Hybrid       176
31                      PETERBILT               Natural Gas       120
32                     MITSUBISHI                  Gasoline       118
33                        PONTIAC                  Gasoline       114
34                      OTHER/UNK                       Unk       114
35                        PORSCHE                  Gasoline       109
36                         SATURN                  Gasoline        99
37  NORTH AMERICAN BUS INDUSTRIES               Natural Gas        99
38                            Unk                       Unk        99
39                            GMC                 Flex-Fuel        56
40                          HONDA               Natural Gas        49
41                  CRANE CARRIER                  Gasoline        48
42                          DODGE  Diesel and Diesel Hybrid        43
43                       CHRYSLER                  Gasoline        33
44                     THOMAS BUS               Natural Gas        31
45                      NEW FLYER           Hybrid Gasoline        30
46                           FORD  Diesel and Diesel Hybrid        25
47                          SMART                  Gasoline        24
48                      PETERBILT  Diesel and Diesel Hybrid        22
49                        AUTOCAR               Natural Gas        19
50                       CADILLAC                  Gasoline        13
51                          VOLVO                  Gasoline        13
52                          HONDA           Hybrid Gasoline        12
53                       CADILLAC                 Flex-Fuel        11

In [2]:
df = pd.read_excel('vehicles_by_make_fuel_2009_zip.xlsx')

# Define a dictionary to map old Fuel names to new names
fuel_mapping = {
    'Gasoline': 'Gasoline',
    'Other': 'Other',
    'Diesel and Diesel Hybrid': 'Diesel Fuel',
    'Natural Gas': 'Compressed Natural Gas (CNG)',
    'Hybrid Gasoline': 'Gasoline',
    'Flex-Fuel': 'Ethanol (E-85)',
    'Battery Electric': 'Electricity',
    'Plug-in Hybrid': 'Electricity',
    'Hydrogen Fuel Cell': 'Electricity',
    # Add more mappings if needed
}

# Replace the Fuel names with the assigned names using the replace method
df['Fuel'] = df['Fuel'].replace(fuel_mapping)

# Print the DataFrame to see the updated data
print(df)

                             Make                          Fuel  Vehicles
0                          TOYOTA                      Gasoline     36974
1                       OTHER/UNK                      Gasoline     27449
2                           HONDA                      Gasoline     25636
3                          NISSAN                      Gasoline     11850
4                           LEXUS                      Gasoline      6270
5                            FORD                      Gasoline      6253
6                   MERCEDES-BENZ                      Gasoline      5931
7                       CHEVROLET                      Gasoline      4924
8                          TOYOTA                      Gasoline      4587
9                             BMW                      Gasoline      4488
10                      OTHER/UNK                Ethanol (E-85)      3780
11                          SCION                      Gasoline      3382
12                      OTHER/UNK                   Diesel Fuel      2779
13                        HYUNDAI                      Gasoline      2696
14                     VOLKSWAGEN                      Gasoline      2498
15                      OTHER/UNK                      Gasoline      2397
16                          ACURA                      Gasoline      1715
17                            KIA                      Gasoline      1637
18                          DODGE                      Gasoline      1635
19                      CHEVROLET                Ethanol (E-85)      1476
20                       INFINITI                      Gasoline      1014
21                           FORD                Ethanol (E-85)       662
22                           AUDI                      Gasoline       571
23                          MAZDA                      Gasoline       515
24                            GMC                      Gasoline       468
25                      OTHER/UNK  Compressed Natural Gas (CNG)       444
26                   FREIGHTLINER                   Diesel Fuel       419
27                           MINI                      Gasoline       340
28                           JEEP                      Gasoline       338
29                         SUBARU                      Gasoline       285
30                  INTERNATIONAL                   Diesel Fuel       176
31                      PETERBILT  Compressed Natural Gas (CNG)       120
32                     MITSUBISHI                      Gasoline       118
33                        PONTIAC                      Gasoline       114
34                      OTHER/UNK                           Unk       114
35                        PORSCHE                      Gasoline       109
36                         SATURN                      Gasoline        99
37  NORTH AMERICAN BUS INDUSTRIES  Compressed Natural Gas (CNG)        99
38                            Unk                           Unk        99
39                            GMC                Ethanol (E-85)        56
40                          HONDA  Compressed Natural Gas (CNG)        49
41                  CRANE CARRIER                      Gasoline        48
42                          DODGE                   Diesel Fuel        43
43                       CHRYSLER                      Gasoline        33
44                     THOMAS BUS  Compressed Natural Gas (CNG)        31
45                      NEW FLYER                      Gasoline        30
46                           FORD                   Diesel Fuel        25
47                          SMART                      Gasoline        24
48                      PETERBILT                   Diesel Fuel        22
49                        AUTOCAR  Compressed Natural Gas (CNG)        19
50                       CADILLAC                      Gasoline        13
51                          VOLVO                      Gasoline        13
52                          HONDA                      Gasoline        12
53                       CADILLAC                Ethanol (E-85)        11

In [3]:
# Define a dictionary to map old Make names to new names
make_mapping = {
    'TOYOTA': 'Toyota',
    'OTHER/UNK': 'Other',
'TOYOTA': 'Passenger Car',
'FORD': 'Passenger Car', 
'CHEVROLET': 'Passenger Car', 
'HONDA': 'Passenger Car', 
'LEXUS': 'Passenger Car', 
'NISSAN': 'Passenger Car', 
'DODGE': 'Passenger Car', 
'MERCEDES-BENZ': 'Passenger Car', 
'BMW': 'Passenger Car', 
'HYUNDAI': 'Passenger Car', 
'VOLKSWAGEN': 'Passenger Car', 
'JEEP': 'Passenger Car', 
'SUBARU': 'Passenger Car', 
'KIA': 'Passenger Car', 
'GMC': 'Passenger Truck',
'MAZDA': 'Passenger Car', 
'ACURA': 'Passenger Car', 
'AUDI': 'Passenger Car', 
'RAM': 'Passenger Truck',
'INFINITI': 'Passenger Car', 
'TESLA': 'Passenger Car', 
'CADILLAC': 'Passenger Car', 
'SCION': 'Passenger Car', 
'PORSCHE': 'Passenger Car', 
'CHRYSLER': 'Passenger Car', 
'VOLVO': 'Passenger Car', 
'MINI': 'Passenger Car', 
'FREIGHTLINER': 'Light Commercial Truck',
'LAND ROVER': 'Passenger Car', 
'BUICK': 'Passenger Car', 
'MITSUBISHI': 'Passenger Car', 
'Unk': 'Other',
'LINCOLN': 'Passenger Car', 
'PONTIAC': 'Passenger Car', 
'PETERBILT': 'Combination Long-haul Truck',
'SATURN': 'Passenger Car', 
'JAGUAR': 'Passenger Car', 
'MERCURY': 'Passenger Car', 
'KENWORTH': 'Combination Long-haul Truck',
'INTERNATIONAL': 'Combination Long-haul Truck',
'ISUZU': 'Single Unit Short-haul Truck',
'HUMMER': 'Passenger Truck',
'FIAT': 'Passenger Car', 
'SUZUKI': 'Passenger Car', 
'OLDSMOBILE': 'Passenger Car', 
'WORKHORSE': 'Light Commercial Truck',
'GENESIS': 'Passenger Car', 
'HINO': 'Single Unit Short-haul Truck',
'SAAB': 'Passenger Car', 
'PLYMOUTH': 'Passenger Car', 
'ALFA ROMEO': 'Passenger Car', 
'AUTOCAR': 'Single Unit Short-haul Truck',
'RIVIAN': 'Passenger Car', 
'GEO': 'Passenger Car', 
'BLUE BIRD': 'School Bus',
'GILLIG': 'Transit Bus',
'THOMAS BUS': 'School Bus',
'NEW FLYER': 'Transit Bus',
'ROADMASTER': 'Single Unit Short-haul Truck',
'MACK': 'Combination Long-haul Truck',
'UNKNOWN': 'Other',
'BENTLEY': 'Passenger Car', 
'FERRARI': 'Passenger Car', 
'MASERATI': 'Passenger Car', 
'IC BUS LLC': 'School Bus',
'SMART': 'Passenger Car', 
'POLESTAR': 'Passenger Car', 
'SPARTAN': 'Combination Long-haul Truck',
'IC BUS': 'School Bus',
'VAN HOOL': 'Transit Bus',
'PIERCE': 'Refuse Truck',
'EL DORADO': 'Transit Bus',
'KALMAR': 'Light Commercial Truck',
'ROLLS-ROYCE': 'Passenger Car', 
'WESTERN STAR': 'Combination Long-haul Truck',
'MOTOR COACH INDUSTRIES': 'Transit Bus',
'BYD COACH AND BUS': 'Transit Bus',
'NORTH AMERICAN BUS INDUSTRIES': 'Transit Bus',
'AMERICAN LAFRANCE': 'Transit Bus',
'KOVATCH MOBLIE EQUIPMENT CORP': 'Other Buses',
'STERLING': 'Combination Long-haul Truck',
'CRANE CARRIER': 'Combination Short-haul Truck',
'LAMBORGHINI': 'Passenger Car', 
'FLXIBLE TRANSIT COACHES': 'Transit Bus',
'ORION': 'Transit Bus',
'ASTON MARTIN': 'Passenger Car', 
'HME': 'Combination Short-haul Truck',
'PREVOST': 'Transit Bus',
'CRUISE': 'Passenger Car',
'AM GENERAL': 'Combination Short-haul Truck',
'LUCID': 'Passenger Car', 
'TMC': 'Single Unit Long-haul Truck',
'GLOBAL ENVIRONMENTAL': 'Transit Bus',
'KOVATCH': 'Other Buses',
'TICO': 'Single Unit Long-haul Truck',
'WHITE/GMC': 'Single Unit Long-haul Truck',
'GREENPOWER MOTOR': 'Transit Bus',
'NORTH AMERICAN': 'Transit Bus',
'NEOPLAN': 'Transit Bus',
'ALLIANZ': 'Combination Short-haul Truck',
'WHITE': 'Light Commercial Truck',
'XOS': 'Transit Bus',
'LODAL': 'Transit Bus',
'PROTERRA': 'Transit Bus',
'ARBOC': 'Transit Bus',
'BLUEBIRD': 'School Bus',
'MOTOR COACH IND': 'Transit Bus',
'MAN TRUCK AND BUS CORPORATION': 'Combination Long-haul Truck',
'CAPACITY': 'Single Unit Short-haul Truck',
'EMERGENCY ONE': 'Refuse Truck',
'BRIGHTDROP': 'Passenger Truck',
'VPG': 'Passenger Car', 
'CATERPILLAR': 'Single Unit Long-haul Truck',
'COUNTRY COACH': 'Motor Home',
'SPECIAL CONSTRUCTION': 'Other',
'FWD': 'Single Unit Short-haul Truck',
'SEAGRAVE': 'Refuse Truck',
'TROLLEY': 'Transit Bus',
'ALEXANDER DENNIS': 'Transit Bus',
'MG': 'Passenger Car', 
'ORANGE EV': 'Transit Bus',
'OSHKOSH': 'Combination Short-haul Truck',
'LOTUS': 'Passenger Car', 

    # Add more mappings if needed
}

# Replace the Make names with the assigned names using the replace method
df['Make'] = df['Make'].replace(make_mapping)

# Print the DataFrame to see the updated data
print(df)

                            Make                          Fuel  Vehicles
0                  Passenger Car                      Gasoline     36974
1                          Other                      Gasoline     27449
2                  Passenger Car                      Gasoline     25636
3                  Passenger Car                      Gasoline     11850
4                  Passenger Car                      Gasoline      6270
5                  Passenger Car                      Gasoline      6253
6                  Passenger Car                      Gasoline      5931
7                  Passenger Car                      Gasoline      4924
8                  Passenger Car                      Gasoline      4587
9                  Passenger Car                      Gasoline      4488
10                         Other                Ethanol (E-85)      3780
11                 Passenger Car                      Gasoline      3382
12                         Other                   Diesel Fuel      2779
13                 Passenger Car                      Gasoline      2696
14                 Passenger Car                      Gasoline      2498
15                         Other                      Gasoline      2397
16                 Passenger Car                      Gasoline      1715
17                 Passenger Car                      Gasoline      1637
18                 Passenger Car                      Gasoline      1635
19                 Passenger Car                Ethanol (E-85)      1476
20                 Passenger Car                      Gasoline      1014
21                 Passenger Car                Ethanol (E-85)       662
22                 Passenger Car                      Gasoline       571
23                 Passenger Car                      Gasoline       515
24               Passenger Truck                      Gasoline       468
25                         Other  Compressed Natural Gas (CNG)       444
26        Light Commercial Truck                   Diesel Fuel       419
27                 Passenger Car                      Gasoline       340
28                 Passenger Car                      Gasoline       338
29                 Passenger Car                      Gasoline       285
30   Combination Long-haul Truck                   Diesel Fuel       176
31   Combination Long-haul Truck  Compressed Natural Gas (CNG)       120
32                 Passenger Car                      Gasoline       118
33                 Passenger Car                      Gasoline       114
34                         Other                           Unk       114
35                 Passenger Car                      Gasoline       109
36                 Passenger Car                      Gasoline        99
37                   Transit Bus  Compressed Natural Gas (CNG)        99
38                         Other                           Unk        99
39               Passenger Truck                Ethanol (E-85)        56
40                 Passenger Car  Compressed Natural Gas (CNG)        49
41  Combination Short-haul Truck                      Gasoline        48
42                 Passenger Car                   Diesel Fuel        43
43                 Passenger Car                      Gasoline        33
44                    School Bus  Compressed Natural Gas (CNG)        31
45                   Transit Bus                      Gasoline        30
46                 Passenger Car                   Diesel Fuel        25
47                 Passenger Car                      Gasoline        24
48   Combination Long-haul Truck                   Diesel Fuel        22
49  Single Unit Short-haul Truck  Compressed Natural Gas (CNG)        19
50                 Passenger Car                      Gasoline        13
51                 Passenger Car                      Gasoline        13
52                 Passenger Car                      Gasoline        12
53                 Passenger Car                Ethanol (E-85)        11

In [4]:
# Group the DataFrame by 'Make' and 'Fuel' and calculate the sum of 'Vehicles'
grouped_df = df.groupby(['Make', 'Fuel'])['Vehicles'].sum().reset_index()

# Print the DataFrame to see the updated data
print(grouped_df)

                            Make                          Fuel  Vehicles
0    Combination Long-haul Truck  Compressed Natural Gas (CNG)       120
1    Combination Long-haul Truck                   Diesel Fuel       198
2   Combination Short-haul Truck                      Gasoline        48
3         Light Commercial Truck                   Diesel Fuel       419
4                          Other  Compressed Natural Gas (CNG)       444
5                          Other                   Diesel Fuel      2779
6                          Other                Ethanol (E-85)      3780
7                          Other                      Gasoline     29846
8                          Other                           Unk       213
9                  Passenger Car  Compressed Natural Gas (CNG)        49
10                 Passenger Car                   Diesel Fuel        68
11                 Passenger Car                Ethanol (E-85)      2149
12                 Passenger Car                      Gasoline    124074
13               Passenger Truck                Ethanol (E-85)        56
14               Passenger Truck                      Gasoline       468
15                    School Bus  Compressed Natural Gas (CNG)        31
16  Single Unit Short-haul Truck  Compressed Natural Gas (CNG)        19
17                   Transit Bus  Compressed Natural Gas (CNG)        99
18                   Transit Bus                      Gasoline        30

In [5]:
# Save the filtered DataFrame as an Excel file (xlsx)
#grouped_df.to_excel('make_Fuel_Vehicles_2018_zip.xlsx', index=False)

In [6]:
# Calculate the total of the 'Vehicles' column in the grouped DataFrame
total_vehicles = grouped_df['Vehicles'].sum()
print("Total number of vehicles:", total_vehicles)

Total number of vehicles: 164890

In [7]:
# Calculate the total of the 'Vehicles' column in the grouped DataFrame
total_vehicles = grouped_df['Vehicles'].sum()
print("Total number of vehicles:", total_vehicles)

Total number of vehicles: 164890

In [8]:
# Filter out rows where 'Make' or 'Fuel' are labeled exactly as 'Other'
grouped_df = grouped_df[~(grouped_df['Make'].str.strip() == 'Other') & ~(grouped_df['Fuel'].str.strip() == 'Other')]


# Print the DataFrame to see the updated data
print(grouped_df)

                            Make                          Fuel  Vehicles
0    Combination Long-haul Truck  Compressed Natural Gas (CNG)       120
1    Combination Long-haul Truck                   Diesel Fuel       198
2   Combination Short-haul Truck                      Gasoline        48
3         Light Commercial Truck                   Diesel Fuel       419
9                  Passenger Car  Compressed Natural Gas (CNG)        49
10                 Passenger Car                   Diesel Fuel        68
11                 Passenger Car                Ethanol (E-85)      2149
12                 Passenger Car                      Gasoline    124074
13               Passenger Truck                Ethanol (E-85)        56
14               Passenger Truck                      Gasoline       468
15                    School Bus  Compressed Natural Gas (CNG)        31
16  Single Unit Short-haul Truck  Compressed Natural Gas (CNG)        19
17                   Transit Bus  Compressed Natural Gas (CNG)        99
18                   Transit Bus                      Gasoline        30

In [9]:
# Calculate the total of the 'Vehicles' column in the grouped DataFrame
total_vehicles = grouped_df['Vehicles'].sum()
print("Total number of vehicles:", total_vehicles)

Total number of vehicles: 127828

In [10]:
# Filter out rows where 'Make' or 'Fuel' are not labeled exactly as 'Other'
filtered_df = df[(df['Make'] == 'Other') | (df['Fuel'] == 'Other')]

print(filtered_df)

     Make                          Fuel  Vehicles
1   Other                      Gasoline     27449
10  Other                Ethanol (E-85)      3780
12  Other                   Diesel Fuel      2779
15  Other                      Gasoline      2397
25  Other  Compressed Natural Gas (CNG)       444
34  Other                           Unk       114
38  Other                           Unk        99

In [11]:
# Calculate the total of the 'Vehicles' column in the grouped DataFrame
total_vehicles = filtered_df['Vehicles'].sum()
print("Total number of vehicles:", total_vehicles)

Total number of vehicles: 37062

In [13]:
127828+37062

164890